### ISSUE TITLE
 Hook execution failed: Net::ReadTimeout

### ISSUE THREAD

**Issue by wangsanshao** [nangongchengfeng/Chat-CodeReview#6]
本地的服务，test的时候，gitlab webhook，超时问题。
本地的日志里面是正常打印cr的内容的。这个有遇到吗，怎么解决，或者该从哪个方面解决

**Comment by nangongchengfeng** [comment]
这个就是网络的问题吧。

客户端（gitlab）

服务端（就这个程序）

你在 gitlab的Linux 服务，telnet 你这个程序的ip 和 端口 是否正常工作。

看是否有错误，请提供更详细的日志

**Comment by wangsanshao** [comment]
![企业微信截图_b17d82c4-e291-42f7-a340-26913781727b](https://github.com/nangongchengfeng/Chat-CodeReview/assets/14011258/4fcfb6e4-ad6f-4b93-8b8d-8efcfcb5b2e4)
 不检测vue就是可以

**Comment by nangongchengfeng** [comment]
vue 这一块我没怎么测试，我这边主要是java 和 py 代码，你可以测试一下

**Comment by wangsanshao** [comment]
![企业微信截图_013007db-59c0-4990-8ee1-abf84cb18022](https://github.com/nangongchengfeng/Chat-CodeReview/assets/14011258/8b5b989b-97eb-46cf-9663-84ac62803bf6)

日志文件里面是正常cr的结果

**Comment by wangsanshao** [comment]
感觉很慢，超过10s，就超时了

**Comment by nangongchengfeng** [comment]
这一块的内容，回根据gitlab的接口 进行评论。这部分没使用到webhook吧。
webhook只是在 gitlab项目进行推送时，程序获取他们的提交的文件吧

如果超时，可以优先调整超时时间
